### ISSUE TITLE
tool for language identification

### ISSUE THREAD

**Issue by jorgtied** [Helsinki-NLP/OpusTools#1]
Create a tool for adding language identification to each sentence of a corpus (in XML) using pycld2 (https://pypi.org/project/pycld2/) or langid.py (https://github.com/saffsd/langid.py):
```
<s cld2="en" cld2conf="0.98" langid="en" langidconf="0.89" id="...
```
opus_read should then also be able to filter on language labels (also combined with confidence value thresholds).

**Comment by miau1** [comment]
`add_lang_ids` script is now ready. Still need to update `opus_read` to be able to filter by language language labels.

**Comment by jorgtied** [comment]
could we rename the frontend script to `opus_langid` instead? I'd like to keep the opus prefix for the tools in this package and also like to keep names short. What kind of formats can this script now work with? Does it work with tokenized (the files in xml) and untokenized texts (the ones in raw)? Does it work with both, zipped archives of files and single xml files?

**Comment by miau1** [comment]
`opus_langid` works with tokenized and raw xml files in both, single xml files and xml files in zip archives. The script is also now more memory efficient than the first version, as it does not load the whole xml tree into memory at once. `opus_read` is able to filter by language labels.
