### ISSUE TITLE
Opus_read: SentenceParserError

### ISSUE THREAD

**Issue by Stamenov** [Helsinki-NLP/OpusTools#12]
Hey,
I am trying to download and concat a bunch of English Bulgarian corpora and the EMEA seem problematic.
It wouldn't fail gracefully so it breaks the whole pipeline, with the following configuration:

```
common: 
  output_directory: "."
steps: 
  - 
    parameters: 
      corpus_name: EMEA
      preprocessing: xml
      release: v3
      source_language: en
      src_output: EMEA.en.gz
      target_language: bg
      tgt_output: EMEA.bg.gz
    type: opus_read
```
With the following error:

```
File "/data/anaconda/envs/traingoo/lib/python3.7/site-packages/opustools-0.0.54-py3.7.egg/opustools/parse/block_parser.py", line 76, in parse_line
    '{error}'.format(document=self.document.name, error=e.args[0]))
opustools.parse.sentence_parser.SentenceParserError: Sentence file "EMEA/xml/bg/humandocs/PDFs/EPAR/mmrvaxpro/H-604-PI-bg.xml" could not be parsed: not well-formed (invalid token): line 17, column 16
```

**Comment by Stamenov** [comment]
Furthermore, I am getting an error with EuBookshop dataset:

`opustools.opus_read.AlignmentParserError: Alignment file "./EUbookshop_v2_xml_bg-en.xml.gz" could not be parsed: mismatched tag: line 225123, column 2
`

**Comment by miau1** [comment]
Unfortunately, those files are not proper xml and currently opus_read crashes if the parsing fails. In the future, we might have an update where opus_read continues to run even if some of the files are not proper xml.

**Comment by miau1** [comment]
The latest version of OpusTools, 1.0.0, opus_read continues parsing from the next sentence file if a sentence file with invalid xml is encountered. If there is an error in an alignment file, the file is parsed up to the error, but cannot be parsed any further. There are plans to fix broken xml files in Opus.

**Comment by ZenBel** [comment]
Keeping this thread alive by reporting the same issue with `opustools 1.3.1` and the following command:

```
opus_read --directory EUbookshop \
    --suppress_prompts \
    --source en \
    --target ar \
    --preprocess raw \
    --leave_non_alignments_out \
    --write_mode moses \
    --write EUbookshop.en.ar.txt
```

The error reads:
```
opustools.parse.alignment_parser.AlignmentParserError: Error while parsing alignment file: Document './EUbookshop_latest_xml_ar-en.xml.gz' could not be parsed: mismatched tag: line 1767, column 2
```
