### ISSUE TITLE
opus_express not checking correctly root directory

### ISSUE THREAD

**Issue by ZJaume** [Helsinki-NLP/OpusTools#16]
Hi,

I have previously downloaded some corpora with `opus_get`. After that, `opus_express` does not found the already downloaded files and asks to download them again.
```bash
$ opus_get -q -s en -t mt -p raw -d DGT -dl downloads/en-mt
$ ll downloads/en-mt
downloads/en-mt/DGT_latest_raw_en.zip  downloads/en-mt/DGT_latest_raw_mt.zip  downloads/en-mt/DGT_latest_xml_en-mt.xml.gz
$ opus_express --root-dir downloads/en-mt -s en -t mt -c DGT
Skipping DGT (no en-mt)...
Checking out DGT...
No alignment file "downloads/en-mt/DGT/latest/xml/en-mt.xml.gz" or "./DGT_latest_xml_en-mt.xml.gz" found
The following files are available for downloading:

  17 MB https://object.pouta.csc.fi/OPUS-DGT/v2019/xml/en-mt.xml.gz
   1 GB https://object.pouta.csc.fi/OPUS-DGT/v2019/xml/en.zip
 401 MB https://object.pouta.csc.fi/OPUS-DGT/v2019/xml/mt.zip

   2 GB Total size
Downloading 3 file(s) with the total size of 2 GB. Continue? (y/n)
```

Thanks!

**Comment by miau1** [comment]
Root directory and download directory are different. `--root_dir` option looks for files that are stored on specific servers in specific file structures. `-dl` option puts and looks for files in a directory in another file structure. The `--download-dir` option was missing from opus_express, I added it now, thanks for noticing. (Actually, now that I think about it, we could probably make the download directory have the same structure as the root directory, which would remove the need for two directory options.)
