### ISSUE TITLE
malformed tmx from opus_read

### ISSUE THREAD

**Issue by keith555** [Helsinki-NLP/OpusTools#25]
I made some small changes to the code to work around issue 24.
The tmx file was produced but there is a mismatch in the tags.
E.g.

```
                <tu>
                        <tuv xml:lang="af"><seg>waarom treiter jy die mensheid met oorlog , pes , hongersnood ?</seg></tuv>
                        <tuv xml:lang="en"><seg>Hold !</seg></tuv>
                </tu>

                        <tuv xml:lang="en"><seg>Why dost thou scourge mankind with War , Plague , Famine ?</seg></tuv>
                </tu>
```
There is a blank line where there should be an opening `<tu>` attribute. This is repeated throughout the file. It's possible that I introduced the error with my code modifications. I've already checked, and I'll check again and update here if I find anything.

**Comment by miau1** [comment]
See issue #24
