### ISSUE TITLE
Add progress indicator to opus_express

### ISSUE THREAD

**Issue by aarnetalman** [Helsinki-NLP/OpusTools#27]
When downloading large amounts of data using `opus_express`  it would be useful to see some indication of the progress. Now it is hard to guess when the job will be finished.

**Comment by miau1** [comment]
Thanks for the feedback and sorry about the delay. `opus_read` now produces better progress messages in verbose mode and `opus_express` uses `opus_read` in verbose mode by default in OpusTools 1.2.3

**Comment by miau1** [comment]
Thanks for the feedback and sorry about the delay. `opus_read` now has better progress messages in verbose mode and `opus_express` uses `opus_read` in verbose mode by default in OpusTools 1.2.3
