### ISSUE TITLE
Misleading logging information in opus_express

### ISSUE THREAD

**Issue by aarnetalman** [Helsinki-NLP/OpusTools#28]
The following lines in `opus_express` produce misleading logging info. 
https://github.com/Helsinki-NLP/OpusTools/blob/da63fc3c44d2e8ddc5aba4ecb3e488bc6076fb37/opustools_pkg/bin/opus_express#L105-L106
The output printed indicates that data for the given language pair is not available in the mentioned collection and that the collection will be skipped, which is not the case.

**Comment by miau1** [comment]
True, the `OpusRead` command will try to download the files anyway and produce appropriate logging info if the files are actually not found. This message is now removed. Thanks!
