### ISSUE TITLE
Is it possible to download all corpus associate with the given language pair?

### ISSUE THREAD

**Issue by BrightXiaoHan** [Helsinki-NLP/OpusTools#29]

**Comment by miau1** [comment]
Yes, you can do this with the [`opus_get` script](https://github.com/Helsinki-NLP/OpusTools/blob/master/opustools_pkg/README.md#opus_get). For example, you can first list all corpus files for English and German, and then download them:

```
opus_get -s en -t de -l
opus_get -s en -t de
```
