### ISSUE TITLE
implement opus-filter

### ISSUE THREAD

**Issue by jorgtied** [Helsinki-NLP/OpusTools#3]
Add a tool for corpus cleaning like in the WMT 2019 tasks. A simple script that can be used for any OPUS bitext and the result is a xces align file or filtered moses-style data. The script should combine language identification, language model filters, alignment-based filters, character code filters, etc ...

**Comment by gertva** [comment]
not sure if I can ask questions here, but I got stuck on this when I try to download a TMX from the OPUS JW300 set. It has nothing to do with the set, I think. 

```
Alignment file /proj/nlpl/data/OPUS/JW300/latest/xml/en-ta.xml.gz not found. The following files are available for downloading:

   8 MB https://object.pouta.csc.fi/OPUS-JW300/v1/xml/en-ta.xml.gz
 263 MB https://object.pouta.csc.fi/OPUS-JW300/v1/xml/en.zip
  94 MB https://object.pouta.csc.fi/OPUS-JW300/v1/xml/ta.zip

 365 MB Total size
Downloading 3 file(s) with the total size of 365 MB. Continue? (y/n) y
JW300_latest_xml_en-ta.xml.gz ... 100% of 8 MB
JW300_latest_xml_en.zip ... 100% of 263 MB
JW300_latest_xml_ta.zip ... 100% of 94 MB
Traceback (most recent call last):
  File "your_script.py", line 3, in <module>
    opus_reader.printPairs()
  File "C:\Users\gertv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\opustools_pkg\opus_read.py", line 350, in printPairs
    lastline = self.readAlignment(gzipAlign)
  File "C:\Users\gertv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\opustools_pkg\opus_read.py", line 308, in readAlignment
    lastline = self.outputPair(self.par, line)[1]
  File "C:\Users\gertv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\opustools_pkg\opus_read.py", line 251, in outputPair
    self.sendPairOutput(wpair)
  File "C:\Users\gertv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\opustools_pkg\opus_read.py", line 210, in sendPairOutput
    self.resultfile.write(wpair[0])
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 83-89: character maps to <undefined>

```
I have no idea how to fix this. Your help is highly appreciated.

**Comment by e-matusov** [comment]
Hi, not sure if this is related, but I get these prompts with `opus_read` that the file is not found, and then the right file is suggested. Can you adjust the paths so that the users don't have to manually enter "y" and the download will begin automatically? Thanks!
`Alignment file /proj/nlpl/data/OPUS/JW300/v1/xml/en-hi.xml.gz not found. The following files are available for downloading:

   6 MB https://object.pouta.csc.fi/OPUS-JW300/v1/xml/en-hi.xml.gz
 263 MB https://object.pouta.csc.fi/OPUS-JW300/v1/xml/en.zip
  75 MB https://object.pouta.csc.fi/OPUS-JW300/v1/xml/hi.zip

 344 MB Total size
Downloading 3 file(s) with the total size of 344 MB. Continue? (y/n) y`

**Comment by miau1** [comment]
> not sure if I can ask questions here, but I got stuck on this when I try to download a TMX from the OPUS JW300 set. It has nothing to do with the set, I think.
> 
> ```
> Alignment file /proj/nlpl/data/OPUS/JW300/latest/xml/en-ta.xml.gz not found. The following files are available for downloading:
> 
>    8 MB https://object.pouta.csc.fi/OPUS-JW300/v1/xml/en-ta.xml.gz
>  263 MB https://object.pouta.csc.fi/OPUS-JW300/v1/xml/en.zip
>   94 MB https://object.pouta.csc.fi/OPUS-JW300/v1/xml/ta.zip
> 
>  365 MB Total size
> Downloading 3 file(s) with the total size of 365 MB. Continue? (y/n) y
> JW300_latest_xml_en-ta.xml.gz ... 100% of 8 MB
> JW300_latest_xml_en.zip ... 100% of 263 MB
> JW300_latest_xml_ta.zip ... 100% of 94 MB
> Traceback (most recent call last):
>   File "your_script.py", line 3, in <module>
>     opus_reader.printPairs()
>   File "C:\Users\gertv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\opustools_pkg\opus_read.py", line 350, in printPairs
>     lastline = self.readAlignment(gzipAlign)
>   File "C:\Users\gertv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\opustools_pkg\opus_read.py", line 308, in readAlignment
>     lastline = self.outputPair(self.par, line)[1]
>   File "C:\Users\gertv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\opustools_pkg\opus_read.py", line 251, in outputPair
>     self.sendPairOutput(wpair)
>   File "C:\Users\gertv\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\opustools_pkg\opus_read.py", line 210, in sendPairOutput
>     self.resultfile.write(wpair[0])
>   File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
>     return codecs.charmap_encode(input,self.errors,encoding_table)[0]
> UnicodeEncodeError: 'charmap' codec can't encode characters in position 83-89: character maps to <undefined>
> ```
> 
> I have no idea how to fix this. Your help is highly appreciated.

I moved this to a new issue, see https://github.com/Helsinki-NLP/OpusTools/issues/4

**Comment by miau1** [comment]
> Hi, not sure if this is related, but I get these prompts with `opus_read` that the file is not found, and then the right file is suggested. Can you adjust the paths so that the users don't have to manually enter "y" and the download will begin automatically? Thanks!
> 
> `Alignment file /proj/nlpl/data/OPUS/JW300/v1/xml/en-hi.xml.gz not found. The following files are available for downloading:
> 
> 6 MB https://object.pouta.csc.fi/OPUS-JW300/v1/xml/en-hi.xml.gz
> 263 MB https://object.pouta.csc.fi/OPUS-JW300/v1/xml/en.zip
> 75 MB https://object.pouta.csc.fi/OPUS-JW300/v1/xml/hi.zip
> 
> 344 MB Total size
> Downloading 3 file(s) with the total size of 344 MB. Continue? (y/n) y`

Version `0.0.42` now has the flag `-q` to suppress download confirmation prompt, see https://github.com/Helsinki-NLP/OpusTools/issues/5

**Comment by miau1** [comment]
See https://github.com/Helsinki-NLP/OpusFilter
