### ISSUE TITLE
DB for off-line search

### ISSUE THREAD

**Issue by jorgtied** [Helsinki-NLP/OpusTools#35]
Add the possibility to create and use an off-line index of OPUS data instead of relying on the public OPUS-API. opus-tools could build a local DB in the same as the OPUS-API update script is doing and then query that database to find resources and how to download them. This would be very convenient to reduce dependence on some on-line service that might break or might have some downtime. Also add an update option that can refresh that local index DB.

**Comment by miau1** [comment]
Implemented in version 1.5.3
