### ISSUE TITLE
change in OPUS yaml files

### ISSUE THREAD

**Issue by jorgtied** [Helsinki-NLP/OpusTools#40]
There has been a slight change in the yaml files in OPUS: the item 'latest release' is now renamed to 'latest_release' (with underscore instead of space). This also affects the OPUS-API and any db update.

**Comment by svirpioj** [comment]
This has been fixed in https://github.com/Helsinki-NLP/OpusTools/commit/6a4af89b6d4883efb25c17ddfa9cbd0f0024a69a
