### ISSUE TITLE
Question: monolingual dialogs (Finnish language)

### ISSUE THREAD

**Issue by remotejob** [Helsinki-NLP/OpusTools#7]
I try create Finnish language Chatbot. 
Question: Is it possible create dialog pairs using OpusTools?
Something like:

`No joo se on totta <tab> Mitä on mielessäsi`

Any help, hints etc.. appreciated.
Kiitos.

**Comment by miau1** [comment]
OpusTools cannot really create any pairs, it just reads existing ones and outputs them in a desired format. By default, it reads translation corpora from OPUS, but you can also read local files. So if you already have the dialog pair data in a format that OpusTools can read (XCES alignment files and XML sentence files), then you can output the dialog pairs separated by tabs, but this is probably not what you are looking for. 

You could download the monolingual Finnish data from OpenSubtitles from https://object.pouta.csc.fi/OPUS-OpenSubtitles/v2018/xml/fi.zip, but it doesn't have the speakers labeled so it is not trivial to extract dialog pairs.

**Comment by remotejob** [comment]
Sure it's not trivial extract pairs.

I am looking something like:

https://www.cs.cornell.edu/~cristian/Cornell_Movie-Dialogs_Corpus.html

In case if arrive something like this, pls let me know.
For last 6 months I was harvesting Twitter. At least something.

Kiitos.
